### ISSUE TITLE
Feature Request - Math 

### ISSUE THREAD

**Issue by kmon6369** [mxtommy/Kip#108]
To be able to add math functions to data and to be able to add multiple data points together.  For example, add the output from 3 solar controllers together to have a total output that could be displayed and graphed.

**Comment by slurcott** [comment]
I thought this too, but then realized you can use the nodered plugin to do what ever functions you want

**Comment by godind** [comment]
Kip's design goal is as a navigation instrument panel. As suggested above there are better suited app for this. Thanks for the suggestion and keep them coming!
