### ISSUE TITLE
Latest Master doesn't build

### ISSUE THREAD

**Issue by silentcossack** [mxtommy/Kip#111]
Latest Master doesn't build, missing "@biacsics/ng-canvas-gauges": "^6.0.7" from package.json. Adding it fixes the build. I'm on Ubuntu 20.04 if that helps.

**Comment by godind** [comment]
Thank you for the info! In the process of updating to Angular 13 plus a bunch of dependency. The fix should be bundled in once completed.

**Comment by silentcossack** [comment]
Glad to hear it! So should I not be using latest then? What's the recommended stable commit?

**Comment by godind** [comment]
Fixed
