### ISSUE TITLE
Feature Request: Change to Night Mode automatically

### ISSUE THREAD

**Issue by RhumbRunner** [mxtommy/Kip#136]
I conceive of a checkbox in the Kip settings that will allow kip to without further input change to night mode based on a SK path like environment.sun = "night" and revert to day mode on "day". The derived data plugin can create this data from position and time of day.

**Comment by JonyIvy** [comment]
+1

**Comment by miggat** [comment]
+1

**Comment by slurcott** [comment]
+2

**Comment by godind** [comment]
Good idea! I'll add this as part of the auto full screen enhancement request. Coming very soon..

**Comment by godind** [comment]
Feature completed and released as of v2.2.0.

Thanks for the great idea. Anything that makes KIP a valuable sailing asset is a win.

Send your requests!
