### ISSUE TITLE
BUG: West Longitudes show negatives

### ISSUE THREAD

**Issue by Rhumb-Runner** [mxtommy/Kip#162]
If this is my current position in SK data browser...
{
  "longitude": -117.23187871379345,
  "latitude": 32.500518317789535
}
KIP displays: (Latitude / Longitude in seconds) 1 Integer / 4 Decimal Places...
32* 30' 01.87" N
117* -13' -54.76" W

Not a big deal just caught my eye.

**Comment by godind** [comment]
I think we need a coordinates widget. The numeric widget does not handle positions well. It's an ugly patch and prone to bugs. We plan on having a AIS and such so we need to get to it.
