### ISSUE TITLE
Display simple switch on/off

### ISSUE THREAD

**Issue by DerTom1978** [mxtommy/Kip#165]
hello,
I can not find a way to display a simple switch. Light on/off or shore power on/off.

Can you include such a possibility? - Or have I overlooked something?

br
tom

**Comment by godind** [comment]
Hi,

Thanks for reaching out. There is a widget called button or switch control for that purpose. Note that you need a device token or to use the login feature to be able to write to Signal K (to send data) and enable the Widget control's Put Request option. Put is the mechanism use to write to SK.

There was a bug with that control some time back. See if you Kip version works, else update to the latest.

Enjoy!

**Comment by DerTom1978** [comment]
hi, thanks for your quick reply.
But I can find a widget called button or switch control.

Basic: Blank, Numeric, Text, State
Gauge: Linear electrical, Liniear Gauge, Radial Gauge, Steeal Gauge
Components: Historical, Wind, Autopilot, Webpage, Tutorial

I can't find anything for a button/switch here.
Where do I have to search?

Many greetings
Tom

Am Do., 19. Jan. 2023 um 15:32 Uhr schrieb David G ***@***.***

**Comment by godind** [comment]
It should be in the list you stated. Do you have the latest version of the app?

**Comment by tvr256** [comment]
It's named "State" and included in Tom's list above. I had no idea it would work as a switch until I tried just now. Would it be better to name it "Switch" instead?

**Comment by EdKok** [comment]
Would like to see more config options like choosing the background color for boolean true or false and font sizing.

**Comment by godind** [comment]
It will now be called Button/Switch control in the next release. I'll work on a better visual and probably add a light panel widget so we can have a condensed light board.

O Nav light
O Bilge Pump
O ...

see #174 for follow up
