### ISSUE TITLE
N2K Autopilot rudder gauge sensor emitting inverted values

### ISSUE THREAD

**Issue by chalentech** [mxtommy/Kip#169]
The rudder angle indicator at the top of the N2K Autopilot gauge (Component) backwards (inverted) starboard should be +.

version 1.3.0

**Comment by godind** [comment]
What is your AP model/setup? Works fine on my boat. Can you also include a screenshot?

**Comment by chalentech** [comment]
![rudderangle](https://user-images.githubusercontent.com/82870703/217597264-6ef214a0-6985-411d-92d6-bada93c624c6.png)

![PXL_20230208_164558224_2](https://user-images.githubusercontent.com/82870703/217597171-e04850be-4469-4425-9396-bff2e00b4edf.jpg)

P70r control head 
ev-1 course computer e70096
Raymarine Rotary Rudder Reference Transducer

**Comment by godind** [comment]
I don't have access to hardware at the moment due to winter season here. It will take something to look into this but I will get to it.

Thanks for the information.

**Comment by godind** [comment]
I've done some investigation and your rudder sensor, the rather the N2K device converting the sensor data, is sending inverted values. That's what I see when compared to other user's and mine.

I'll and an invert rudders option.

Of note: in you screenshot I noticed you have multiple devices emitting values for the same paths. This can potentially be an issue (not related to the problem at hand) if you do not select a source. Both sources will overwrite each other for that given path in KIP. You should either configure SK source priority or check that a source is selected in KIP and not source "default". The latest UI should prevent this problem.

**Comment by Mastery972** [comment]
Hi guys!
I have exactly the same issue. My autopilot is a Simrad AC20 with a Simrad AP16 screen.
Rudder is ok on AP16 screen and also on my Raymarine a65 MFD.
Unfortunately, it appears inverted with N2k Autopilot. I use the latest version of the plugins with a Victron Cerbo GX. I was not able to find an option to display it correctly.
Best regards,
Y.

**Comment by Mastery972** [comment]
> > Hi guys!
> > I have exactly the same issue. My autopilot is a Simrad AC20 with a Simrad AP16 screen.
> > Rudder is ok on AP16 screen and also on my Raymarine a65 MFD.
> > Unfortunately, it appears inverted with N2k Autopilot. I use the latest version of the plugins with a Victron Cerbo GX. I was not able to find an option to display it correctly.
> > Best regards,
> > Y.
> 
> Can you share the SK Data Browser path value please? This will help. I probably just need to add an invert rudder option to the widget but want to make sure.

Hi godind
Find some screenshots here.
![Screenshot_20240609_175011_Chrome](https://github.com/mxtommy/Kip/assets/172119532/fd633eba-c088-4bdb-8cce-ca807293fd9b)
![Screenshot_20240609_174349_Chrome](https://github.com/mxtommy/Kip/assets/172119532/3f09fcd2-5df4-4dea-82ac-13b9d96d6683)

Best regards,
Y.

**Comment by godind** [comment]
Hi,

Thanks for this. Sorry but I should have asked for more details before!

Because I have no hardware to test this, can you share SK's published Rad values from your install at:

Full Port:
Full Staboard:

It's probably positive on port and negative on stb but the range will also help.

Thanks

**Comment by Mastery972** [comment]
Hi godind
Find here some screenshots of what you asked for:
![Screenshot_20240610_190406_Chrome~2](https://github.com/mxtommy/Kip/assets/172119532/b9f04fb9-517c-46aa-8c9a-9b1f830af987)

![Screenshot_20240610_190428_Chrome~2](https://github.com/mxtommy/Kip/assets/172119532/447e6a76-9512-41d7-be87-c19adf4b970e)
 
![Screenshot_20240610_190449_Chrome~2](https://github.com/mxtommy/Kip/assets/172119532/f0879cf2-c757-427b-ab5a-25ca4f078f8b)

Best regards,
Y.

**Comment by godind** [comment]
@Mastery972 @chalentech feature published in v2.11.0. Have fun!

**Comment by Mastery972** [comment]
Thanks a lot!
It works well in latest version (2.10.1).

Best regards,
Y.

**Comment by godind** [comment]
My pleasure.
