### ISSUE TITLE
Negative zone alarms triggering incorrectly

### ISSUE THREAD

**Issue by tvr256** [mxtommy/Kip#170]
I have a depth gauge widget displaying depth below keel.

If I configure an Alarm zone with empty lower value and upper value set to 0, the alarm triggers with positive depth values. I would expect it only to trigger with negative values.

**Comment by godind** [comment]
@tvr256 Strange because you should nor be able save this setup. Empty lower and upper of 0 is not accepted. Can you please double check. Thank you

**Comment by tvr256** [comment]
I've double checked, and I can save empty lower and upper of 0 in 2.4.2 :

![image](https://github.com/mxtommy/Kip/assets/117984987/9a9fa9e2-fdc1-4682-b652-4259290c8e16)

**Comment by godind** [comment]
I'll take a look. It should account from 0 down to negative infinity but it's probably the opposite.

Does it work if you do from -10000 to 0?
