### ISSUE TITLE
Moving average to signalk data before kip display

### ISSUE THREAD

**Issue by ignamendi21** [mxtommy/Kip#199]
Hello, 
First of all, thank you for the help I received so I have been available, finally to run my own builds locally.  :)

I have KIP and signalk  to display data in my boat. However the data is very "discrete", I can see how the AWA is changing every second with too big steps. 35-43-32-39-33-43, etc... I know that this is what the sensor is actually measuring and that it is correct, however it is not very usefull to see such a big change in the values. I was wondering if there is  a way to apply some kind of **moving average** to the data, so the data I show with kip is the average taking into a count the las 5 values (for example)

**Comment by godind** [comment]
Hi

Thanks for the feedback. V2.0.1 has a new feature to throttle data update. In this release all widgets only emit data every 500ms so it should be a bit smoother.

In the next release this configuration field will be exposed in the paths options tab. It is not at the moment.

Hope this helps

**Comment by ignamendi21** [comment]
@godind thank you for.your awnser!. When may it be released?

**Comment by godind** [comment]
Working on some bugs. Will get to it after. Hard to say since it's on the Night Shift 😉
