### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by netAction** [mxtommy/Kip#2]
- always show 2-4 values on vertical axis but at least one per 100px
- scroll the Animation horizontal, not vertical
- cleanup horizontal scale
- remove circles when they would be close to each other, the values are more accurate where the value changes than where the circles are
- determine the rounding in given data and allow the smooth graph to show any value in possible interval
- add the current value as watermark or in lower left corner (usually only the high values are interesting)

![current](https://user-images.githubusercontent.com/1829847/32267703-79e66ad2-beec-11e7-9722-d1db08ad7cf9.PNG)
![maybe](https://user-images.githubusercontent.com/1829847/32267707-7e2fef46-beec-11e7-8cc3-9ceb886605e8.png)

![current2](https://user-images.githubusercontent.com/1829847/32271318-ada3c89e-bef9-11e7-8a11-655774103169.PNG)
![maybe2](https://user-images.githubusercontent.com/1829847/32271323-af967412-bef9-11e7-84c5-5247c5514ffd.png)

**Comment by godind** [comment]
Reduced the number of ticks. Not perfect but easier to read. Recommend using Embed Webpage widget and link to Grafana if good data visualization is required. The histogram widget is meant for simple overtime data tendency monitoring. Like is wind speed increasing in the last hour.
