### ISSUE TITLE
Allow offline use via PWA

### ISSUE THREAD

**Issue by mxtommy** [mxtommy/Kip#21]
https://medium.com/@nsmirnova/creating-pwa-with-angular-5-part-2-progressifying-the-application-449e3a706129

:)

**Comment by VibroAxe** [comment]
I'm not sure that this needs "offline" use as without the connection to the signal K server it's going to be pretty useless anyway. However, a PWA to allow this to be installed as a seperate fullscreen app without needing to toggle fullscreen as you go in/out of the browser would be super helpful and much simpler. I'll see if I can throw a PR together for this at some point
