### ISSUE TITLE
How do I load configuation in 2.2.1

### ISSUE THREAD

**Issue by markante** [mxtommy/Kip#218]
I just updated to 2.2.1 and have the issue that I can not find the way to load my global/server configuation with the new storage management. Is all my work I put in the config gone and I can not load it anymore ?

Thanks for your help

**Comment by godind** [comment]
Hi. It should have upgraded the local browser config. Unless you had never connected to KIP with that device. Is this the case?

Good news is it's not gone!

Look for ~/.signalk/applicationData/global/kip/1.0.0.json. Make a backup.

Rename to 9.0.0.json and see if you can see it from KIP Configuration tab.

If you use Sign in. You have to copy global to "user / default".

If not using Sign in, copy to local storage.

**Comment by markante** [comment]
Thank you very much. Will try to do it with the jason. Have a nice day. I really like kip

**Comment by godind** [comment]
Me pleasure. Let me know if it works.

**Comment by godind** [comment]
Just released 2.2.2 that fixes configuration upgrade issues. Try it out and provide feedback.

Thanks for your patience!

**Comment by godind** [comment]
FYI. V2.2.2 was released and fixes the problem. Please try this version and report back. Thank you!
