### ISSUE TITLE
HH:MM:SS broken in 2.2.2

### ISSUE THREAD

**Issue by Rhumb-Runner** [mxtommy/Kip#223]
Just updated to 2.2.2, I had several widgets that were converting seconds to HH:MM:SS. After updating they show blank. When I change to seconds the values are shown. But, as soon as changed back to HH:MM:SS goes blank again.

**Comment by godind** [comment]
Hi. Thanks for the report.

I not sure I follow completely. May I ask what widget, path, value  type and if you are using unit conversions.

This help us reproduce the problem troubleshoot. We recently fixed an issue that was very similar.

**Comment by godind** [comment]
Also. Have you tried the new date widget. It might be better suited to you needs?

**Comment by godind** [comment]
Hi,

I've tried but I cannot reproduce this issue. I'll need more details. See above.

Thank you

**Comment by godind** [comment]
Actually, I'm 90% certain the Date Value Display Widget will fix your problem. Let me know and I'll close.

Thanks

**Comment by RhumbRunner** [comment]
![image](https://github.com/mxtommy/Kip/assets/65317903/e6120eb7-b1b0-4885-971f-cfd6b175163d)
![image](https://github.com/mxtommy/Kip/assets/65317903/1e4a34f4-082a-4f07-8904-ac55232e508e)

Date Value widget doesn't work with the values my timer module (node-red) puts out. The path is not even available to the widget. The path just has the numerical value of the seconds left.  I like the new timer widget but I have a slightly different module that also does pursuit starts. When I go into KIP's data browser and change the units to HH:MM:SS it's correct.

![image](https://github.com/mxtommy/Kip/assets/65317903/7c0785df-ec45-4af5-9adb-7fbe34983310)
![image](https://github.com/mxtommy/Kip/assets/65317903/a9acb67c-ab92-41db-80f9-32543ec77e70)

**Comment by godind** [comment]
As a side note, the date time widget will only work with valid SK date format.

Maybe there is bug in the time transform to hhmmss. Make sure the value is a valid number in seconds with no decimals.

**Comment by godind** [comment]
Ok. I got it now. I'll check why the value on 600 is not working with hh:mm:ss. This will take a some time.
