### ISSUE TITLE
Some numeric values dont update

### ISSUE THREAD

**Issue by zubenubi** [mxtommy/Kip#23]
I notice that my Kip values for outside temperature dont change unless I refresh the browser page. The path is environment.outside.temperature and I am displaying in degrees F.

**Comment by mxtommy** [comment]
Eeek, super late on this issue sorry! 
There should not be any reason for this. Only thing I can think of is the source being different. See if there are multiple sources available for the path. (dropdown to the right of where you specify path).

If you still have issues you can reply here, but I suggest you look up the SignalK slack chat. Very easy to get support there :)
