### ISSUE TITLE
feature requests. wind widget COG

### ISSUE THREAD

**Issue by petsicola** [mxtommy/Kip#257]
I saw that you added a graphic that tells you the direction to the waypoint. It would also be ideal to mark the COG.
something like the number 3 picture.

![image](https://github.com/mxtommy/Kip/assets/61534583/e69e1063-87c7-4727-a16f-54bb8b4ee76e)

**Comment by godind** [comment]
Good ideas. Could you split this feature in two? One for wind widget COG and another for a new widget with average variations chart?
