### ISSUE TITLE
Fullscreen state detection

### ISSUE THREAD

**Issue by JonyIvy** [mxtommy/Kip#259]
On some interactions, the browser brings the app from fullscreen mode back to non-fullscreen mode (not using the fullscreen menu item). Then the app still shows "Exit Fullscreen" in the menu. It seems like KIP is not aware of its own fullscreen state.
So to go back to full screen, you have to select "Exit Fullscreen", then the menu item changes to "Fullscreen", you press it and you have fullscreen again.
It would be better if the app were aware of the fullscreen state and could show the menu item correctly at all times. There should be listeners for fullscreen state change.

**Comment by godind** [comment]
Hi,

Sadly browsers don't allow tracking of F11 key or Full Screen state. It's a browser limitation. All browsers work a bit differently and so we use a framework for this. It does not work at all on mobile OSs - you need to install as an app to get the browser UI out of the way.

It's not something we can fix.
