### ISSUE TITLE
Wind Instrument "Laylines" incorrect

### ISSUE THREAD

**Issue by tvr256** [mxtommy/Kip#261]
If I'm understanding it correctly, the "Layline Angle" in the wind instrument has nothing to do with laylines, It would be better named the "Close Hauled Angle" or the "No Go Zone".

https://en.wikipedia.org/wiki/Layline
https://en.wikipedia.org/wiki/Point_of_sail

Also, the lines should be based on Apparent wind. Currently they are based on True wind.

**Comment by godind** [comment]
I agree with **Show close haul** and not **Show Laylines**. It should also be **Tacking angle** and not **Layline angle**. Don't know why it was labeled this way originally. I've noticed but no one ever reported this as an issue. Maybe my latest UI cleanup is attracting user! It's a simple label fix.

I also agree on apparent wind!

I think there is a racing plugin or some derived data available that covers some of those calculations that could used to further enhance the widget. I'll check with the team. If you can help understanding what's available it would speed up things.
