### ISSUE TITLE
The numbers is not visble on the compass on the widget autopilot

### ISSUE THREAD

**Issue by rezder** [mxtommy/Kip#262]
When using the theme moderne dark the background and text color of is too similar.  I believe it happened when the autopilot got its own text color on #202

**Comment by godind** [comment]
Send a screenshot. It looks fine on my side

**Comment by godind** [comment]
Make sure you are on the latest version please. This is the only version supported. If you are trying to get up to date with your fork, you should rebase. You are 200+ commits behind. Save yourself some work ;)

**Comment by rezder** [comment]
my master is from 19/12 and my rebase is from 26/11 this is a screnshot
![Screenshot at 2023-12-22 11-07-51](https://github.com/mxtommy/Kip/assets/18736370/6d2a7b39-4e2b-4c14-8dc1-c63d369bad7b)
the numbers is missing. You need two text classes to handle two different background light-ring numbers (120) dark-ring text (NW) you have only one. And I am testing my rebase now.

**Comment by godind** [comment]
This dark color is because the button are disabled. It's intentionnal.

Thank for reporting!

**Comment by rezder** [comment]
come on where the arrow is pointing the number 30 is missing thank you fro listenting

**Comment by rezder** [comment]
The numbers are on the  light ring same color as text NW but you can not see them  30 60 90 120 150 where are they??. There are even space for them. Tell me the color class of the html text elements that holds the numbers 30 60  and the color.

**Comment by rezder** [comment]
![Screenshot at 2023-12-22 16-42-37](https://github.com/mxtommy/Kip/assets/18736370/569f6914-18cd-40e9-b9e0-84ca403b24ce)
This is the template look there is number on it
