### ISSUE TITLE
Min/Max font too small in Numeric Display Widget

### ISSUE THREAD

**Issue by kmon6369** [mxtommy/Kip#285]
Great System!!    With the latest version the Min and Max values in the Numeric Display Widget have a very small font.  It scales when the widget is made larger or smaller but is still small.  Can a larger font or ratio of the min/max font to the value font be changed to make it easier to read?

**Comment by Aitonos** [comment]
I find the same issue, and it can easily be fixed as the UNIT font size is quite bigger than the MIN/MAX .

I want to add that there is some lack of contrast in the titles of each frame, as grey color over black it is hardly readble under sun light.

And as a constructive comment would like to remark that the WIND Gauge data is almost unreadable as the indication drops for apparent and real winds are too small.

However, KIP is lovely, thanks! 
![Imagen de WhatsApp 2024-04-01 a las 23 01 39_51575962](https://github.com/mxtommy/Kip/assets/148384749/b6f1caa7-8ae3-4b41-9103-10496364e0e3)
