### ISSUE TITLE
Alarms not displaying, some reapear

### ISSUE THREAD

**Issue by chrisryan43** [mxtommy/Kip#317]
Cross posted from Slack (as requested by @godind 

I have tried to create an alarm around my bilge alarm. I can see the alarm in Data Browser but when i activate it i dont see the alert in KIP. What am i doing wrong? (interestingly i do have a rogue alarm notification in KIP but when i try to open up the notificaiton to mute it there is nothing there)

**Comment by godind** [comment]
![image](https://github.com/mxtommy/Kip/assets/34038713/4eb47852-7957-45a1-b04a-9829657c7d1a)

![image](https://github.com/mxtommy/Kip/assets/34038713/6b168d4b-be72-4033-91e8-bc57e8eb8685)

**Comment by godind** [comment]
Adding detail: some alarms reappear after being acknowledged such as the Sk upgrade message.

**Comment by JonyIvy** [comment]
+1 for the (1) tag at the notifications box, when I click on it, there's nothing in the menu (only mute or unmute alarm)

**Comment by godind** [comment]
Hi,

Would someone have a node-red pattern to share so I can test this?

**Comment by chrisryan43** [comment]
> Hi,
> 
> Would someone have a node-red pattern to share so I can test this?

I'm unable to reproduce this isue now......

**Comment by godind** [comment]
Not a problem. There was a bug that lead to a simpler design and tighter SL integration. Releasing shortly.
