### ISSUE TITLE
Login/Logout Authentication Infinite Loop

### ISSUE THREAD

**Issue by jtroyer76** [mxtommy/Kip#318]
Kip can get into an infinite loop when signalk authorization token is set to never expire in security settings.

![image](https://github.com/mxtommy/Kip/assets/16786752/6a5030e3-de97-4477-96ee-0e0f30f6a5e2)

Here is a snip from the console log:
![image](https://github.com/mxtommy/Kip/assets/16786752/999899da-7755-4756-a93d-e8392cf4121f)

The issue is KIP tries to decode the expiration date of the token which is not set.

A workaround is to set the expiration to 10d or any other valid value.

**Comment by godind** [comment]
It is cause by the NEVER value in the Signal K / Security / Remember ME Timeout parameter.

Change the parameter to "1d" or another value for a temporary fix.

**Comment by instantchow** [comment]
Is this out a problem with the SK + KIP "out of the box" I think I hit this issue/or something very similar when I initially attempted to turn on Authentication (to get token and use remote storage)

In my instance:

`/admin/#/security/settings` 

Doesn't show "NEVER" it was simply blank.

**Comment by godind** [comment]
As of sk v2.6 it is the default parameter value. Its recent issue that Kip needs a fix for.

Not sure why it's blank... I think the UI does not allow NEVER but in the config file its probably set to never. Put 1d in SK, save and restart. It should fix it.
