### ISSUE TITLE
Zones displayed incorrectly if zone and gauge units don't match

### ISSUE THREAD

**Issue by tvr256** [mxtommy/Kip#348]
Zones should be converted from the zone units to the gauge units before displaying on the gauge.

Example:

For a SignalK field with units "ratio", set up the following zones with units "ratio":

![image](https://github.com/mxtommy/Kip/assets/117984987/aedc3934-3af7-42f1-acbf-fbd6aa55af94)

Create a radial gauge with units "ratio", the zones are displayed correctly (number error raised separately as #347):

![image](https://github.com/mxtommy/Kip/assets/117984987/e1287e61-cf2f-46c8-b754-4202863ca5ee)

Change the gauge units from "ratio" to "Percentage value". The gauge pointer displays correctly and the zone alarms still trigger correctly, but the zones are not displayed correctly on screen. The zones should be converted from the zone units to the gauge units before displaying.

![image](https://github.com/mxtommy/Kip/assets/117984987/3bdb84fb-0958-45f3-a2e8-5cd817a37a6b)

**Comment by tvr256** [comment]
Hi @godind , this fix doesn't seem to work for me. Gauges with larger numbers work fine, but a ratio (0-1) gauge doesn't display any zone information now:

![image](https://github.com/mxtommy/Kip/assets/117984987/7d83d128-2ad4-4765-904e-376afab38b69)

![image](https://github.com/mxtommy/Kip/assets/117984987/6e39baec-4dec-4a91-85b0-43b42b396a33)

**Comment by godind** [comment]
Grr... it's that bug where fractional numbers such as 1/3 can't be represented properly in JavaScript. Same as the ticks numbers. I'll fix it in the next release!

**Comment by godind** [comment]
Coed in next release
