### ISSUE TITLE
feat: logarithmic scaling for radial gauge

### ISSUE THREAD

**Issue by x7y8z9** [mxtommy/Kip#359]
![Radial gauge current](https://github.com/mxtommy/Kip/assets/143433271/572a1246-f23f-4bd5-a581-74d3d2be244e)
I created a radial gauge for summarized charge/discharge current of two 24V battery banks. 
I'm interested in the details (amp by amp) up to 15-20A. Between 120 and 150A, it doesn't matter to view 2 or 3A. 
I would actually have to extend the display scale to 200A, but unfortunately the display range at the lower end would then disappear completely.
The solution would be logarithmic scaling.

**Comment by godind** [comment]
I've done some research and tried a few approaches but I've not found out how. Logarithmic scale are exponential scale and so it's not what we you need. It will do the opposite where the large number are the focus ie. with a scale of from 0, 1 ,10 ,100 , 1000 Amps,  all evenly spaced. So it make it worst. I've looked at square root, and a cushion approach where I do the math the create a non linear progression but the gauge library does not support all I need. It's either that the needle does not move according to the scale or the ticks are off.

I've not found a mathematical way... yet. If you have an idea, let me know and I'll try...
