### ISSUE TITLE
Scrollbar on Chromium/RPi

### ISSUE THREAD

**Issue by JonyIvy** [mxtommy/Kip#365]
On Chromium on Raspberry Pi there is a scrollbar that doesn't go away, and is also shown in fullscreen mode. Current version: 2.9.1, but this started with version 2.8.0-beta.2 (maybe 2.8.0-beta.1 but that version didn't work at all on my machine). On 2.7.1-beta.2 everything was still ok, no scrollbar.

<img width="1370" alt="Bildschirmfoto 2024-04-04 um 13 00 00" src="https://github.com/mxtommy/Kip/assets/6115974/a0895477-b846-40d7-9816-24ea94898542">
<img width="1370" alt="Bildschirmfoto 2024-04-04 um 12 59 27" src="https://github.com/mxtommy/Kip/assets/6115974/47c0a241-0690-4546-9261-0ca0a7aea504">

**Comment by jimmyendt** [comment]
i have the same! also tried to make vhromium on 90% but the scrollbar is still visible

**Comment by godind** [comment]
Good catch. We will fix it!
