### ISSUE TITLE
Multiply percentage by dimensional value to get quantity

### ISSUE THREAD

**Issue by bkcorwin** [mxtommy/Kip#384]
I am using the gauges in kip to display information from a maretron fpm100 tank level sensing system.  The only fields it seems to report through signalk are tank capacity (gallons) and percentage remaining (%).  What i'd love is to be able to multiply these together so that I can display the gauge in gallons.  

Is there a way to do this?  

Thanks
Brian

**Comment by godind** [comment]
See the Maretron plugin. That might get the data into signal k. The using derive data plugin I think you would see the tank appear and can set tank shape and volume. Once configured, you will see it in KIP. Ask in Discord server channel. They will help you

**Comment by bkcorwin** [comment]
Ah, cheers.  It actually works just using the derived data plugin.  The maretron sensors are broadcasting a percentage based on a tank shape calibration that was done on the maretron side.  So just multiplying that percentage by the capacity in the derived data plugin works great.

I was mistakenly hoping to just do that simply in kip but looks like no need

**Comment by godind** [comment]
Enjoy!
