### ISSUE TITLE
Side scroller appearing on interface, no way to remove

### ISSUE THREAD

**Issue by markpires123** [mxtommy/Kip#386]
Since I updated to the latest version, I've noticed all my browsers show a side scroller on the right. I can just barely nudge the page up and down with this. I reset my configs, deleted them, created a new one but still see this side scroller and it affect the overall layout of my previous pages.

**Comment by markpires123** [comment]
I dunno if its the latest version with openplotter,  but I was able to fix it but adding overflow:hidden to the css in the root of public directory. styles.6af848a7c959e550.css  I added it to the body of app-root.

**Comment by godind** [comment]
Fixed in next version by making navbar buttons larger to accomplish for larger touch area.

**Comment by godind** [comment]
fixed in #385
