### ISSUE TITLE
feat: add compas support for Rad units with negative to port

### ISSUE THREAD

**Issue by voilier-kalymnos** [mxtommy/Kip#392]
In baseplate compass mode, negative value don't work.
The range is 0 to 360°, in my case the wind sensor send me data from -180° to 180° 
![wind](https://github.com/mxtommy/Kip/assets/145222002/ba8c3207-52b0-46d4-9b2c-8ccc463eb7d5)

**Comment by godind** [comment]
The compas gauge only support path with positive rad values. Add gauge feature to support for paths rad unit that use negative values (-180 to 180 in degrees).

**Comment by godind** [comment]
@voilier-kalymnos  Not as easy I as thought. I think there might be another path the converts this. Maybe with derived-data. Ask the group again. Else I'll create a dedicated Widget. The marine compass broken as you know...
