### ISSUE TITLE
Submit my contribution - New Gauges and Theme

### ISSUE THREAD

**Issue by godind** [mxtommy/Kip#41]
Hi @mxtommy mxtommy,

I want to build a autopilot widget and since I know little about most of this tech, I started with a theme, then added new linear and radial gauge using ng-canvas-gauges. They all support your themes and config panels. I think I've done a pretty good job for a first timer. I'm not 100% done tuning colors schemes and such to make the gauges look really good but it should take me a few days.

How can I submit this to the project? Sorry but I'm new to this...

Note the Unit label in those screenshots are off: their is no power instrument data in the simulation stream so used paths to different streams just to display something.
 
![Gauge Sample1](https://user-images.githubusercontent.com/34038713/78588244-458c8880-780c-11ea-975f-bc27dff13562.png)
![Gauge Sample2](https://user-images.githubusercontent.com/34038713/78588245-458c8880-780c-11ea-88da-e114d36b84ca.png)
![Gauge Sample3](https://user-images.githubusercontent.com/34038713/78588243-44f3f200-780c-11ea-8d40-f7395e7ea9f1.png)

Thanks

**Comment by mxtommy** [comment]
Hi!

That looks awesome!

For sure I would be happy to merge your contributions! 

Contributions would be easiest by pull request. You mentioned you're new at this. If you think you will contribute to other projects in the future it can't hurt learning how it's done. You can see here:
[https://github.com/firstcontributions/first-contributions](https://github.com/firstcontributions/first-contributions)

I'd be happy to help you if you have any questions with that :)

Alternatively if you would rather, I suppose you could send me a zip file with you changes and I can try merging them manually :)

Thanks!

**Comment by mxtommy** [comment]
PR Merged! Will push new npm version out this weekend!
