### ISSUE TITLE
Update 2.10.0: values not availabe on instrument

### ISSUE THREAD

**Issue by x7y8z9** [mxtommy/Kip#421]
A path/source is availabe in SK as well in KIP data browser and KIP instrument.
But the value of the path/source is available in SK and KIP data browser but not shown at the instrument.

Note: setting the path filter to all shows the path/source, after confirming the filter shows Voltage but not power (electrical.grid.31.power)

SK
![Inverter SK 31power available](https://github.com/mxtommy/Kip/assets/143433271/bfc51d75-4416-4cd3-9f21-f6f2b0e891ee)

KIP data browser
![Inverter KIP data 31power available](https://github.com/mxtommy/Kip/assets/143433271/ab188ca9-a2b6-4edf-bf98-5d047edf7f09)

KIP settings
![Inverter KIP settings 31power](https://github.com/mxtommy/Kip/assets/143433271/94983574-a28c-4584-8282-ee540f554d9d)

KIP settings filter
![Inverter KIP settings 31power filter](https://github.com/mxtommy/Kip/assets/143433271/610a5e0d-3ca6-4ad7-94c8-b158d63b5b62)

KIP instrument
![Inverter KIP instrument0 31power](https://github.com/mxtommy/Kip/assets/143433271/8f088756-27e8-4698-bac2-35d5794e4cdb)

**Comment by godind** [comment]
The path is of type Power with base Units of Watts (W).

Questions:
1- with the filter on all you see the path, right?
2- with the filter to Power (W) do you see the path?
3- with the filter to Voltage (V), you should not see the path. Do you see it?

In your screenshot I see the path  Format as Potential (volts). Is this something you manually set or was it auto populated? Watts source value to volts conversion will not work.

**Comment by x7y8z9** [comment]
See below...

________________________________
Von: David G ***@***.***>
Gesendet: Mittwoch, 29. Mai 2024 16:57
An: mxtommy/Kip
Cc: Joerg R. Plaschka; Author
Betreff: Re: [mxtommy/Kip] Update 2.10.0: values not availabe on instrument (Issue #421)


The path is of type Power with base Units of Watts (W).

Questions:
1- with the filter on all you see the path, right? Yes
2- with the filter to Power (W) do you see the path? Yes
3- with the filter to Voltage (V), you should not see the path. Do you see it? No

[After I saved the path and I open the settings window again it has changed the filter to voltage]
In your screenshot I see the path Format as Potential (volts). Is this something you manually set or was it auto populated? Watts source value to volts conversion will not work.

It's automatically Watt, which is correct for "power". See screenshot.

**Comment by godind** [comment]
I don't see anything below. Maybe the send did not work.

What is the Scale Start and Scale End in the Display options tab?

You are saying that once you select the path, it automatically changes the filter to Voltage and the format to Volts?

**Comment by x7y8z9** [comment]
I put the "see below" into a screenshot attached.

Correct: "You are saying that once you select the path, it automatically changes the filter to Voltage and the format to Volts?"



________________________________
Von: David G ***@***.***>
Gesendet: Donnerstag, 30. Mai 2024 03:59
An: mxtommy/Kip
Cc: Joerg R. Plaschka; Author
Betreff: Re: [mxtommy/Kip] Update 2.10.0: values not availabe on instrument (Issue #421)


I don't see anything below. Maybe the send did not work.

What is the Scale Start and Scale End in the Display options tab?

You are saying that once you select the path, it automatically changes the filter to Voltage and the format to Volts?

**Comment by godind** [comment]
I'll investigate why. From some reason I do not any screenshot after the original post.

**Comment by godind** [comment]
The filter options only serves to filter the path dropdown list when you type to search for a path. Say you want a path of type power: set the filter and start typing. Note that not all paths have proper Units defined so you can use All and Unitless to look for those. Once the path, source and format is stacked and saved, the filter has no effect on the value the widget will produce. When you re-open the widget config, it will be set to Voltage again as it is the default filter for this widget.

I have tested by setting a path Units to W and I do get data. I see that your value is -165.3 and -172. Check that the Display tab options Scale Start/End allow for this range. The default is from 0 to 15.

**Comment by x7y8z9** [comment]
My bad, sorry: scale wasn't defined correct (0 to 5000 instead of -5000 to 0)

Thx!

________________________________
Von: David G ***@***.***>
Gesendet: Donnerstag, 30. Mai 2024 22:04
An: mxtommy/Kip
Cc: Joerg R. Plaschka; Author
Betreff: Re: [mxtommy/Kip] Update 2.10.0: values not availabe on instrument (Issue #421)


The filter options only serves to filter the path dropdown list when you type to search for a path. Say you want a path of type power: set the filter and start typing. Note that not all paths have proper Units defined so you can use All and Unitless to look for those. Once the path, source and format is stacked and saved, the filter has no effect on the value the widget will produce. When you re-open the widget config, it will be set to Voltage again as it is the default filter for this widget.

I have tested by setting a path Units to W and I do get data. I see that your value is -165.3 and -172. Check that the Display tab options Scale Start/End allow for this range. The default is from 0 to 15.
