### ISSUE TITLE
Something weird with pressure units in KIP

### ISSUE THREAD

**Issue by ESchlotfeldt** [mxtommy/Kip#425]
I have SK data source emitting an oil pressure reading of 4500 hPa, while the dial in KIP is displaying 45 hPa. 

Any thoughts? 

Thanks!

**Comment by godind** [comment]
Hi, 
I looked at the code quickly and the Pa to hPa conversion looks fine at first glance.

Can you share a screenshot of the SK data path and value from the SK Data Browser and also from the KIP widget output and Widget Options please?

I'll take a look.

**Comment by ESchlotfeldt** [comment]
Hi - thanks for quick response. below are the files requested. The issue might be that SK uses hPa as its default pressure unit, while KIP uses Pa as the default, ie KIP thinks it receiving Pa data and then converts it into hPa - which is out by a factor of 100 as observed in the screenshots?

![KIP 1](https://github.com/mxtommy/Kip/assets/106944628/051a4410-71e6-4ec2-80d7-87573d3c13c1)
![KIP 2](https://github.com/mxtommy/Kip/assets/106944628/3f4d7881-d5c3-493a-9727-85ac3e571e04)
![KIP 3](https://github.com/mxtommy/Kip/assets/106944628/2d4975cb-3ff5-4b6b-ad1d-ffd5b194ca00)

**Comment by godind** [comment]
I don't see the source emitting this value in your screenshot. The path is different than what's in the specs.
![image](https://github.com/mxtommy/Kip/assets/34038713/229bfec4-9876-4c7f-a92c-be8adb542470)

It's not a problem, but SK's base units type for all pressure values should be Pa, unless I am mistaken. You can ask in the specification channel to validate. 

KIP uses base Units as the starting point for all format conversions.

Until the source is corrected, in KIP, you can set the format to as-is value. This will pass it without modification, but the gauge displayed format will be As-Is. Not best looking but it will work.

**Comment by ESchlotfeldt** [comment]
Ok thanks - thats very helpful!

**Comment by godind** [comment]
Is it your own plugin that is generating the data?

Can I close this issue?

**Comment by ESchlotfeldt** [comment]
Ok to close the issue. I hadn’t realised that Kip needs its input to be in Pa. I’ve changed to that and all is ok now. Thanks for your prompt assistance.On 12 Jun 2024, at 05:01, David G ***@***.***> wrote:﻿
Is it your own plugin that is generating the data?
Can I close this issue?

**Comment by godind** [comment]
Always a pleasure to help. I'll close the issue.

Note: The base Units format is defined by Signal K. Not by KIP. See this lick for path specifications: https://signalk.org/specification/1.7.0/doc/vesselsBranch.html
