### ISSUE TITLE
Can't set decimals in "Radial Steel Style"

### ISSUE THREAD

**Issue by EdKok** [mxtommy/Kip#428]
As opposed to 'Radial'.
![image](https://github.com/mxtommy/Kip/assets/26001736/ef9cbb6c-d7fd-4d84-83d4-4a5a94fee4f4)
![image](https://github.com/mxtommy/Kip/assets/26001736/e0031d6d-9f52-434e-965c-f3d8cc6e4ba4)

**Comment by godind** [comment]
Hi Ed. I'll fix it. It's a simple matter but I'm hard at work on a big v3 UI refit at the moment. 

It'll be next on my list. Unless I have to release a small v2 release to fix important issues. Than I'll bundle it. 

Cheers.
