### ISSUE TITLE
How to use N2K Autopilot?

### ISSUE THREAD

**Issue by ignamendi21** [mxtommy/Kip#429]

**Comment by ignamendi21** [comment]
Is there some information f what is it needed to make it work? What are the depencies?

**Comment by godind** [comment]
I read your question in Discord. Your model is not support, yet. You need a SK plugin that supports your brand/model. Once setup, KIP's AP should work.

Scott Bender ask for some details to add support. He is you best bet as he is one of the founder. Connect with him. He will ask for some n2k data dump to see what n2k sentences you AP uses.

Let me know how it goes once you got this part sorted.

Cheers.
