### ISSUE TITLE
Known good paths show as invalid

### ISSUE THREAD

**Issue by RhumbRunner** [mxtommy/Kip#479]
Known good paths are show as bad when editing widgets. My only thought is it might be something with the plugin. I've only seen this on the plugin I'm working on. The buttons and displays work even though Kip doesn't believe they are good paths.

![image](https://github.com/user-attachments/assets/94b195f3-4b84-489b-b180-d136021f277f)

**Comment by godind** [comment]
I think this is with the old Boolean widget, right? If so, this widget will be retired in the next major release.

Make sure that you are sending a Boolean value and not numeric 1 or 0. The widget filters the results,  unless you check the numeric option the the new widget.
