### ISSUE TITLE
New options request - DataChart Widget

### ISSUE THREAD

**Issue by hugorobi** [mxtommy/Kip#483]
Hi,

For the "Data Chart" widget, it would be interesting to be able to define the length of the history (minutes) as well as the sampling interval.

For example : I would like to display the AWS or AWA for the last 15 minutes.

Hugo

**Comment by godind** [comment]
Have you looked at Datasets configuration? Each Data Chart widget is liked to a dataset. Datasets can be configured almost like you requested but for the sampling rate which is defined by the time scale (sec, min, hrs).

Have a look

**Comment by hugorobi** [comment]
Hi,

Nice, I've found where to create dataset as you mentionned.

Many thanks.



Envoyé depuis mon appareil Galaxy


-------- Message d'origine --------
De : David G ***@***.***>
Date : 2024-11-05 08 h 55 (GMT-05:00)
À : mxtommy/Kip ***@***.***>
Cc : hugorobi ***@***.***>, Author ***@***.***>
Objet : Re: [mxtommy/Kip] New options request - DataChart Widget (Issue #483)


Have you looked at Datasets configuration? Each Data Chart widget is liked to a dataset. Datasets can be configured almost like you requested but for the sampling rate which is defined by the time scale (sec, min, hrs).

Have a look
