### ISSUE TITLE
Load Demo fails

### ISSUE THREAD

**Issue by tkurki** [mxtommy/Kip#6]
On first use `Load Demo` fails with `Cannot GET /@mxtommy/kip/page/0`. Subsequent navigation to /@mxtommy/kip/ fixes things.

**Comment by mxtommy** [comment]
Will be switching to hash based routing which will fix this. :) ETA 1-2 weeks hopefully :)

**Comment by mxtommy** [comment]
Done! Routing now using hashes. also added a 200ms delay to avoid looping in firefox (not sure what caused that)
