### ISSUE TITLE
Hardware e-ink display

### ISSUE THREAD

**Issue by osauzet** [mxtommy/Kip#60]
Hello,
I would like to buy an e-ink tablet in order to display the data from Kip, have you tried some inexpensive models ...? The idea is to use this e-ink screen tablet only for Kip ... no other use ... so that it should be a minimum resource (display / cpu / memory / wifi / storage?)
Thanks in advance !
And thanks for Kip,  it's a great project !
Olivier.S

**Comment by mxtommy** [comment]
Hi Oliver!

I have not tried personally but several have with no success. Unfortunately the limiting factor so far seems to be javascript support in their built-in browsers. Kip is based on the Angular Javascript framework, and the few that have tried have found their browsers are not supported.

Here is the supported browsers: https://angular.io/guide/browser-support (note I havn't tested on all, I usually test only firefox/chrome)

If you can try the tablets in store and they have web access, try loading http://sail.samoht.ca to see if it works :)
