### ISSUE TITLE
Make angular and friends dev dependencies

### ISSUE THREAD

**Issue by tkurki** [mxtommy/Kip#66]
The built static files are all that is needed, right? So there should be 0 runtime deps littering users’ disks.

**Comment by mxtommy** [comment]
Added in  commit 52dedb76cbdb5bc403803408a22cce8aeb356fb7 :) Note looking at https://github.com/SignalK/signalk-server/blob/ef7a30bb00ed98f06b64fa95203e48bf3168e4bd/src/modules.ts#L197 I think it might need the "--production" flag to npm to not install dev dependencies :)
