### ISSUE TITLE
Easy way to connect to "this server"

### ISSUE THREAD

**Issue by tkurki** [mxtommy/Kip#7]
New users who are running their SK server and starting Kip up would probably rather see their own data than demo.signalk.org, so an easy way to configure Kip and connect to the originating server would be great.

If somebody chooses to implement this make sure you take into account the option to run SK server with ssl, so that the protocol is https. Kip works ok with with https/wss urls.

**Comment by mxtommy** [comment]
Already planned :D Will be fixing this and a few other things in the next week or two :)

**Comment by mxtommy** [comment]
Done :) Defaults to window.location.origin. (and also add's /signalk to any url entered)
