### ISSUE TITLE
Feature Request: Text orientation for apparent/true wind

### ISSUE THREAD

**Issue by deadeye12** [mxtommy/Kip#70]
Great work on this!   Not critical, and not sure why it bothers me :-)   but would it be possible to have an option on the compass/wind display show the text for AWA and TWA right side up depending on where the wind was coming from?  For example if you are close hauled, the AWA number is upside down, on a run the true wind angle is upside down.  Could we have the option to have Them flip orientation when it crosses the 'southern' or 'northern' half of the rose, thus being more readable at a rapid glance?  -Thx!

**Comment by godind** [comment]
Not sure I understand. Can you share a screenshot as a concept?

**Comment by godind** [comment]
Just took another look and I think I got it!

Actually working Wind Widget. I'll give it a try!
