### ISSUE TITLE
Feature Request: Rudder Position Indicator

### ISSUE THREAD

**Issue by deadeye12** [mxtommy/Kip#73]
Would it be possible to add an option on one of the linear gauge widgets to only show a single mark vs. coloring from the minimum value up to the value?  The application for this would be a ruder angle indicator.

**Comment by mxtommy** [comment]
Added a new "Color" option on linear gauges, to allow no progress bar (and thickens the needle a bit) a0af75f8d745cd626365e9354830710b44dbdec5 

Note will need to wait for next version to be released :)
