### ISSUE TITLE
Extra /signalk/  in server configuration

### ISSUE THREAD

**Issue by tkurki** [mxtommy/Kip#8]
As the SK specification sets /signalk/  as the standard path I think it would be easier and more strightforward to configure Kip with just protocol + hostname: `http://demo.signalk.org` as opposed to `http://demo.signalk.org/signalk`.

**Comment by mxtommy** [comment]
Personally I like that it's fully supplied as it gives flexibility, though you are right in that it should never change... I'll see if there's a way to have both (default to /signalk if not specified, but if something is specified use that)

**Comment by tkurki** [comment]
Easy enough to probe the suppliead url as is and then append /signalk if there is no proper sk response there.

**Comment by tkurki** [comment]
Personally I think we should strive for doing things the spec way so as not to introduce extra variations. I’ve not been perfect that way, but I aim better...

**Comment by mxtommy** [comment]
Done! if there's not already there it adds it.
