### ISSUE TITLE
Feature Request: Windgauge - indicator bearing to next waypoint

### ISSUE THREAD

**Issue by Sjoerd02** [mxtommy/Kip#82]
To me it would be usefull to have an indicator to the next waypoint in the windgauge.
By having that you can see directly if you can reach it based on the laylines.
On non tacking course you can obviously see if you are heading in right direction.

**Comment by Sjoerd02** [comment]
Thinking over the comment on non-tacking course, you might want to have an extra indicator for COG to see if you are really heading to you waypoint

**Comment by davidsanner** [comment]
Windgauge is a great instrument.  One thing I'd like to see is the ability to diplay data (numerical values) in the space in the corners around the gauge. eg. VMG, STW, or even wind speed (the numbers on the gauge are hard to see on my tablet).

**Comment by godind** [comment]
> Thinking over the comment on non-tacking course, you might want to have an extra indicator for COG to see if you are really heading to you waypoint

I think that navigation relayed info should be handled by the AP gauge, or maybe a new gauge is required. Wind gauge is really all about wind speed, wind angle and tacking. VMG is one gauge you can add to see wind angles vs course performance value.

**Comment by Techstyleuk** [comment]
I really like the B&G SailSteer view and they indicate True wind, Apparent wind, Bearing to Waypoint, heading, COG, Laylines and current direction and speed.  I think KIP has most of this with exception of bearing, COG and current which I think would be a great addition.  I also agree that using the four corners would be great!!

I love this plugin and use it all the time!  thanks for all the work that has been done so far!!

**Comment by godind** [comment]
We will add next point to the wind widget in the next release. Have a look at the new improved UI in the lastest version!

**Comment by petsicola** [comment]
I think that people say something like this.
Number 1 is a graphical current direcction and current speed
Number 2 is the next point. i put here an image. 
I´m sure that you know this B&G Dashboard... but I preffer your new wind gauge theme ;)

![likethis](https://github.com/mxtommy/Kip/assets/61534583/f9f21dcf-a3c5-443d-961d-19ccf7c13445)

**Comment by godind** [comment]
Not exactly the same UI but implemented.
