### ISSUE TITLE
Canvas gauge change position in Firefox

### ISSUE THREAD

**Issue by mxtommy** [mxtommy/Kip#84]
Kip affected by this: https://github.com/Mikhus/canvas-gauges/issues/232

**Comment by godind** [comment]
Can't reproduce the issue with v107.0x. Resolved?

**Comment by philipa** [comment]
I'm here because I've just seen this with 1.3.0, so not resolved.

**Comment by godind** [comment]
Not sure what can be done. It's a dependency issue (a gauge toolkit). Can't you another browser? Firefox is about 2.5% of the market and I doubt the library owner will fix it.

Closing issue...

**Comment by CttCJim** [comment]
I solved it. https://github.com/Mikhus/canvas-gauges/issues/232#issuecomment-4650363083
