### ISSUE TITLE
Feature Request: User defined text

### ISSUE THREAD

**Issue by tmcolby** [mxtommy/Kip#85]
First of all.. wow.. I love this plugin.  Thank you for your effort here.

I would like to be able to use something like the "text" panel and populate it with a user defined string instead of being sourced by a signalk path.  It would be cool to be able to put labels or strings that identify what the page is for.

**Comment by techgardeners** [comment]
I suggest changing the "Blank" widget to "Static text" widget. I would add the configuration button and insert the text to be displayed in it.
I could take care of it if I wanted to

**Comment by JonyIvy** [comment]
+1

**Comment by godind** [comment]
Integrated as of KIP v2.x
