### ISSUE TITLE
Problem displaying gauge

### ISSUE THREAD

**Issue by joma42** [mxtommy/Kip#86]
I am useing mxtommy/kip for a wihle and I am quite happy, But since a while i have a problem displaying linear gauges propper and this only on one page. I created this page new after updating to 1.2.1. 
![Bildschirmfoto von 2021-09-01 18-31-22](https://user-images.githubusercontent.com/89927837/131701068-84e4b905-34ef-4891-9d68-5fd80785b1b4.png)
I have no idea if this can be related. I am grateful for any advice

**Comment by mxtommy** [comment]
Are you using Firefox? Is so might be related to #84 If so not much I can do unfortunately until it's fixed upstream. You can try Chrome though

**Comment by joma42** [comment]
Thaks for your help. 
Using Crome solved the problem of "pixeling" the gauges. 
Unfortunately, it did not solve the problem that the gauges are not updated and the numerical values are not displayed in small fields.

![Bildschirmfoto von 2021-09-07 09-28-18](https://user-images.githubusercontent.com/89927837/132449261-ae3c1c50-3d0c-4f0e-933b-9aa4da2e88e5.png)

After refreshing the page manually all gauges show the correct values but the display is still not updated automatically. When I switch back and forth between pages (inside KIP) all gauges show zero again. This happens with gauges of all types.
The problem with the numeric values not being displayed seems to be a scaling error. If I make the box big enough the values are displayed perfectly.
It would be great if you also have a solution for this.
Thanks in advance

**Comment by godind** [comment]
Can you check again with the latest Kip version please and tell us what hardware, OS and browser version you are using.  We cannot recreate this bug and no one else has reported a similar issue. Thank you

**Comment by godind** [comment]
No response to further investigation. Closing issue as this is the only report is such a problem.
