### ISSUE TITLE
Feature Request: Add N2K Autopilot page to KIP demo template

### ISSUE THREAD

**Issue by mgrouch** [mxtommy/Kip#88]
Feature Request: Add N2K Autopilot page to KIP demo template

Thanks

**Comment by mxtommy** [comment]
Combining issues: Other demo ideas: 
Feature Request: Add engine monitoring gauges page to KIP demo template
Feature Request: Add barograph page to KIP demo template

**Comment by mxtommy** [comment]
So the problem with this, is currently the demo config is pulling data from http://demo.signalk.org which does not have engine or barometer data at this time. Also the autopilot needs some server support as well I think. Not sure how to address that. Have any ideas?

**Comment by godind** [comment]
And... the AP needs a code fix. Coming soon!
