### ISSUE TITLE
Auto scaling of historical chart data

### ISSUE THREAD

**Issue by oyve** [mxtommy/Kip#95]
With air pressure, a fixed Y-axis of say 970-1040 hPa would be within the "norm".
However it's sort of difficult to see changes to the pressure curve with such a big scope.
A solution to this could be to set the min and max range of the Y-axis to be limited to the min max values of the associated data set.

**Comment by mxtommy** [comment]
Hi, you should be able to do this already. In the settings of the widget, where you select the dataset, there's an option "Y axis always start from zero". Un-selecting that (maybe with also setting min/max on the first display tab of the widget config) should get you there :) If that doesn't work let me know!
