### ISSUE TITLE
Feature request: switch buttons

### ISSUE THREAD

**Issue by EdKok** [mxtommy/Kip#98]
Don't know if anyway feasible but to explain:
I have a touch-screen (with a RPi3 behind it) running in kiosk-mode showing Kip. It is great and was very useful last season. But if, for whatever reason, I need access to the desktop I cannot get out of kiosk-mode (there is no mouse/keyboard attached). If I could create a screen with one or more buttons that could trigger for instance a shutdown, close browser or start a script so I could do whatever...

**Comment by mxtommy** [comment]
Hi,

I'm not sure that's something KIP can realistically do. It's running in the browser and has limited access to anything outside the browser (for good reason, imagine if a random webpage could shutdown your computer or run a script :D) 

Closest thing I could think of, is running a service on your RPi that would run something when going to the link? see an example here: https://forums.raspberrypi.com/viewtopic.php?t=58802#p441115
